networks:
  backnet: {}

services:
  mysql-db:
    image: mysql:5.7
    networks:
      - backnet
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: theresumegenerator
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql-db", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10

  api:
    build: services/api/
    networks:
      - backnet
    depends_on:
      mysql-db:
        condition: service_healthy
    links:
      - mysql-db
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - /data:/app/data


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - backnet
    depends_on:
      - mysql-db
    links:
      - mysql-db
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: mysql-db
