version: '1.0'

networks:
  backnet: {}

services:
  db:
    image: mysql:5.7
    command:  --default-authentication-plugin=mysql_native_password
    networks:
      - backnet
    restart: always
    expose:
      - 3306:3306
    # volumes:
    #   - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: theresumegenerator
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      
  api:
    build: services/api/
    networks:
      - backnet
    depends_on:
      - db
    links:
      - db
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - /data:/app/data


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - backnet
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
